apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.3-alpine3.9
    ports:
    - containerPort: 6379
  - name: redis-ui
    image: rediscommander/redis-commander
    ports:
    - containerPort: 8081
